name: Release Package

on:
  push:
    branches:
      - main  # A branch principal que será monitorada para liberar versões

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configura o Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22 # Altere conforme necessário
          registry-url: https://registry.npmjs.org/

      # Instala dependências
      - name: Install dependencies
        run: npm install

      # Listando arquivos changeset para depuração
      - name: List changeset files
        run: ls -la .changeset/

      # Verifica se há releases pendentes no Changesets

      - name: Create Release changeset
        id: changesetsrelease
        run: npx changeset --yes

      - name: Create Release
        id: changesets
        run: npx changeset version --yes

      # Faz o commit das mudanças de versão e changelog geradas pelo Changesets
      - name: Commit release changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .  # Adiciona as mudanças de versão e changelog
          git commit -m "ci: version packages"  # Commit da versão
          git push

      # Executa o build dos pacotes antes de publicar (usando turbo)
      - name: Build packages
        run: npm run build  # Ou "turbo run build" se necessário

      # Publica no npm
      - name: Publish to npm
        run: npx changeset publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
